"""RAG 配置的统一默认值。"""

DEFAULT_RAG_TOP_K = 5
DEFAULT_RAG_INTERVIEW_TOP_K = 4
DEFAULT_RAG_SIMILARITY_THRESHOLD = 0.5
DEFAULT_RAG_TIMEOUT_SECONDS = 3.0
DEFAULT_RAG_CHUNK_SIZE = 700
DEFAULT_RAG_CHUNK_OVERLAP = 70
DEFAULT_RAG_MAX_FILE_SIZE_MB = 10
