"""知识库目录和文档范围管理端口。"""

from typing import Protocol


class RagProjectRepositoryPort(Protocol):
    def list_projects(self) -> list[dict]: ...
    def save_project(self, name: str, aliases: list[str], project_id: str | None = None) -> dict: ...
    def delete_project(self, project_id: str) -> dict: ...
    def validate_document_scope(self, scope_kind: str, project_id: str | None) -> None: ...
    def change_document_scope(self, document_id: str, scope_kind: str, project_id: str | None) -> dict: ...
    def set_document_archived(self, document_id: str, archived: bool) -> dict: ...
